# Generated by Django 6.1 on 2026-09-03 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'service_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('duration_minutes', models.IntegerField()),
                ('unit', models.CharField(default='session', max_length=30)),
                ('min_quantity', models.IntegerField(default=1)),
                ('max_quantity', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='services', to='services.servicecategory')),
            ],
            options={
                'db_table': 'services',
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('DAILY', 'Hằng ngày'), ('WEEKLY', 'Hằng tuần'), ('MONTHLY', 'Hằng tháng'), ('CUSTOM', 'Tùy chỉnh')], max_length=20)),
                ('number_of_sessions', models.IntegerField()),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('package_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='packages', to='services.service')),
            ],
            options={
                'db_table': 'service_packages',
                'ordering': ['service__name', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='services_category_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('base_price__gte', 0)), name='services_base_price_check'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gt', 0)), name='services_duration_minutes_check'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('min_quantity__gt', 0)), name='services_min_quantity_check'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('max_quantity__isnull', True), ('max_quantity__gte', models.F('min_quantity')), _connector='OR'), name='services_max_quantity_check'),
        ),
        migrations.AddConstraint(
            model_name='servicepackage',
            constraint=models.CheckConstraint(condition=models.Q(('number_of_sessions__gt', 0)), name='service_packages_number_of_sessions_check'),
        ),
        migrations.AddConstraint(
            model_name='servicepackage',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100)), name='service_packages_discount_percent_check'),
        ),
        migrations.AddConstraint(
            model_name='servicepackage',
            constraint=models.CheckConstraint(condition=models.Q(('package_price__isnull', True), ('package_price__gte', 0), _connector='OR'), name='service_packages_package_price_check'),
        ),
    ]
