# Generated by Django 6.1 on 2026-09-15 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('section_code', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('form_schema', models.JSONField()),
                ('pricing_config', models.JSONField()),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'services',
                'ordering': ['section_code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='services.service')),
            ],
            options={
                'db_table': 'service_images',
                'ordering': ['-is_primary', 'sort_order', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('sort_order__gte', 0)), name='service_images_sort_order_check')],
            },
        ),
    ]
