# Generated by Django 6.1 on 2026-09-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
