# Generated by Django 6.1 on 2026-09-19 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_alter_service_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceimage",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="services.service",
            ),
        ),
    ]
