# Generated by Django 6.1 on 2026-09-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customeraddress",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="customeraddress",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=14, null=True
            ),
        ),
    ]
