# Generated by Django 6.1 on 2026-10-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0002_alter_customeraddress_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customeraddress",
            name="province_code",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="customeraddress",
            name="ward_code",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=10
            ),
        ),
    ]
