# Generated by Django 6.1 on 2026-09-18 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "distribution_type",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Công khai"),
                            ("CODE_ONLY", "Chỉ nhận bằng mã"),
                            ("ASSIGNED", "Được cấp riêng"),
                        ],
                        default="CODE_ONLY",
                        max_length=20,
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("PERCENT", "Phần trăm"),
                            ("FIXED", "Số tiền cố định"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("issuance_limit", models.IntegerField(blank=True, null=True)),
                ("issued_count", models.IntegerField(default=0)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "vouchers",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("discount_value__gt", 0)),
                        name="vouchers_discount_value_check",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("min_order_amount__gte", 0)),
                        name="vouchers_min_order_amount_check",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("issued_count__gte", 0)),
                        name="vouchers_issued_count_check",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("issuance_limit__isnull", True),
                            ("issuance_limit__gt", 0),
                            _connector="OR",
                        ),
                        name="vouchers_issuance_limit_check",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("issuance_limit__isnull", True),
                            ("issued_count__lte", models.F("issuance_limit")),
                            _connector="OR",
                        ),
                        name="vouchers_issued_within_limit_check",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("discount_type", "FIXED"),
                            ("discount_value__lte", 100),
                            _connector="OR",
                        ),
                        name="vouchers_percent_value_check",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("max_discount_amount__isnull", True),
                            ("max_discount_amount__gt", 0),
                            _connector="OR",
                        ),
                        name="vouchers_max_discount_amount_check",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("discount_type", "PERCENT"),
                            ("max_discount_amount__isnull", True),
                            _connector="OR",
                        ),
                        name="vouchers_fixed_max_discount_null_check",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("start_at__lt", models.F("end_at"))),
                        name="vouchers_time_check",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserVoucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Quản trị viên cấp"),
                            ("CODE", "Nhận bằng mã"),
                            ("PUBLIC", "Tự nhận công khai"),
                            ("CAMPAIGN", "Chiến dịch tự động"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Có thể sử dụng"),
                            ("RESERVED", "Đang được giữ"),
                            ("USED", "Đã sử dụng"),
                            ("REVOKED", "Đã thu hồi"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                ("reserved_at", models.DateTimeField(blank=True, null=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="assigned_user_vouchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="user_vouchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="user_vouchers",
                        to="vouchers.voucher",
                    ),
                ),
            ],
            options={
                "db_table": "user_vouchers",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "voucher"),
                        name="user_vouchers_user_voucher_unique",
                    )
                ],
            },
        ),
    ]
