# Generated by Django 6.1 on 2026-09-26 10:12

import apps.complaints.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_alter_booking_user_voucher"),
        ("complaints", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="complaints",
                to="bookings.bookingschedule",
            ),
        ),
        migrations.AlterField(
            model_name="complaintattachment",
            name="complaint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="complaints.complaint",
            ),
        ),
        migrations.AlterField(
            model_name="complaintattachment",
            name="file",
            field=models.ImageField(
                upload_to=apps.complaints.models.complaint_attachment_path
            ),
        ),
        migrations.AlterField(
            model_name="complaintattachment",
            name="file_type",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
