# Generated by Django 6.1 on 2026-10-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0004_repair_legacy_complaints_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="refund_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
