# Generated by Django 6.1 on 2026-10-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0006_complaint_reporter"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="customer_delta",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="complaint",
            name="outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Không xử lý tiền"),
                    ("REFUND_CUSTOMER", "Hoàn tiền khách"),
                    ("PAY_WORKER", "Trả tiền nhân viên"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="shortfall",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="complaint",
            name="worker_delta",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="reporter_role",
            field=models.CharField(
                choices=[("CUSTOMER", "Khách hàng"), ("WORKER", "Nhân viên")],
                max_length=20,
            ),
        ),
    ]
