# Generated by Django 6.1 on 2026-10-08 09:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_engine', '0003_alter_chatbotmessage_options_chatbotmessage_cards_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('RUNNING', 'Đang xử lý'), ('SUCCEEDED', 'Thành công'), ('FAILED', 'Thất bại')], default='RUNNING', max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('attempt_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('lease_expires_at', models.DateTimeField()),
                ('error_code', models.CharField(blank=True, max_length=60)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('assistant_message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_run', to='ai_engine.chatbotmessage')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='ai_engine.chatbotsession')),
                ('user_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_run', to='ai_engine.chatbotmessage')),
            ],
            options={
                'db_table': 'chatbot_runs',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'RUNNING')), fields=('conversation',), name='chatbot_one_active_run')],
            },
        ),
    ]
