# Generated by Django 6.1 on 2026-10-08 17:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120)),
                ('version', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=250)),
                ('summary', models.TextField(blank=True)),
                ('sections', models.JSONField(default=list, help_text='Danh sách {heading, text}; văn bản thuần.')),
                ('keywords', models.TextField(blank=True)),
                ('role', models.CharField(choices=[('CUSTOMER', 'Khách hàng'), ('WORKER', 'Nhân viên')], default='CUSTOMER', max_length=20)),
                ('source_document', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('DRAFT', 'Bản nháp'), ('PUBLISHED', 'Xuất bản'), ('RETIRED', 'Thu hồi')], default='DRAFT', max_length=20)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title', '-version'],
                'constraints': [models.UniqueConstraint(fields=('slug', 'version'), name='chatbot_help_slug_version')],
            },
        ),
    ]
