# Generated by Django 6.1 on 2026-10-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_helparticle'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='helparticle',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PUBLISHED')), fields=('slug',), name='chatbot_help_one_published'),
        ),
    ]
