# Generated by Django 6.1 on 2026-09-21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('BANK_ACCOUNT', 'Tài khoản ngân hàng'), ('MOMO', 'MoMo'), ('VNPAY', 'VNPAY')], max_length=30)),
                ('usage_type', models.CharField(choices=[('PAYMENT', 'Thanh toán'), ('PAYOUT', 'Nhận tiền')], max_length=20)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('bank_bin', models.CharField(blank=True, max_length=10)),
                ('bank_code', models.CharField(blank=True, max_length=30)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('account_holder_name', models.CharField(blank=True, max_length=150)),
                ('account_number_encrypted', models.TextField(blank=True)),
                ('account_number_last4', models.CharField(blank=True, max_length=4)),
                ('provider_reference', models.CharField(blank=True, max_length=255)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Chưa xác minh'), ('PENDING', 'Đang xác minh'), ('VERIFIED', 'Đã xác minh'), ('FAILED', 'Xác minh thất bại'), ('DISCONNECTED', 'Đã ngắt liên kết')], default='UNVERIFIED', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_payment_methods',
                'ordering': ['-is_default', '-created_at'],
                'indexes': [models.Index(fields=['user', 'usage_type', 'is_active'], name='payment_method_user_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True)), fields=('user', 'usage_type'), name='payment_methods_one_active_default')],
            },
        ),
    ]
