# Generated by Django 6.1 on 2026-10-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_userpaymentmethod"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="checkout_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="payment",
            name="link_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="order_code",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_link_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="payment",
            name="qr_code",
            field=models.TextField(blank=True, default=""),
        ),
    ]
