# Generated by Django 6.1 on 2026-10-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_payment_checkout_url_payment_link_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("CASH", "Tiền mặt"),
                    ("BANK_TRANSFER", "Chuyển khoản"),
                    ("MOMO", "MoMo"),
                    ("VNPAY", "VNPay"),
                    ("CARD", "Thẻ"),
                    ("WALLET", "Ví CleanWise"),
                ],
                max_length=30,
            ),
        ),
    ]
