# Generated by Django 6.1 on 2026-10-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="account_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="payment",
            name="account_number",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="payment",
            name="bank_bin",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="payment",
            name="transfer_content",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
