# Generated by Django 6.1 on 2026-09-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFavoriteWorker',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'customer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='favorite_worker_links',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'worker',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='favorited_by_links',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'customer_favorite_workers',
                'ordering': ['-created_at', '-id'],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('customer', 'worker'),
                        name='customer_favorite_workers_unique',
                    ),
                    models.CheckConstraint(
                        condition=~models.Q(('customer', models.F('worker'))),
                        name='customer_favorite_workers_distinct_users',
                    ),
                ],
            },
        ),
    ]
