# Generated by Django 6.1 on 2026-09-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0002_customerfavoriteworker"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingassignment",
            name="commission_reserved",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
