# Generated by Django 6.1 on 2026-09-28 18:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0008_bookingschedule_reminder_sent_at"),
        ("worker", "0003_bookingassignment_commission_reserved"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="bookingassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACCEPTED")),
                fields=("schedule",),
                name="uniq_accepted_assignment_per_schedule",
            ),
        ),
    ]
