# Generated by Django 6.1 on 2026-10-01 19:22

from django.db import migrations, models


def fill_legacy_ward_codes(apps, schema_editor):
    Area = apps.get_model("worker", "Area")
    areas = Area.objects.using(schema_editor.connection.alias)
    for area in areas.filter(ward_code__isnull=True).iterator():
        # Preserve existing Area IDs and worker links until an explicit reset.
        areas.filter(pk=area.pk).update(ward_code=f"L{area.pk}")


class Migration(migrations.Migration):

    dependencies = [
        ("worker", "0004_bookingassignment_uniq_accepted_assignment_per_schedule"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="area",
            name="areas_city_name_unique",
        ),
        migrations.AddField(
            model_name="area",
            name="province_code",
            field=models.CharField(db_index=True, default="", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="area",
            name="ward_code",
            field=models.CharField(max_length=10, unique=True, null=True),
        ),
        migrations.RunPython(fill_legacy_ward_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="area",
            name="ward_code",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="area",
            name="name",
            field=models.CharField(max_length=150),
        ),
        migrations.AddIndex(
            model_name="area",
            index=models.Index(
                fields=["province_code", "name"], name="areas_province_name_idx"
            ),
        ),
    ]
