# Generated by Django 6.1 on 2026-09-24 04:06

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_booking_delivery_address"),
        ("wallets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("PAYMENT", "Thanh toán dịch vụ"),
                    ("REFUND", "Hoàn tiền"),
                    ("WITHDRAW", "Rút tiền"),
                    ("ADJUSTMENT", "Điều chỉnh"),
                    ("EARNING", "Thu nhập từ đơn"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="WorkerEarning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("CASH", "Tiền mặt"), ("ONLINE", "Thanh toán online")],
                        max_length=20,
                    ),
                ),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                (
                    "commission_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("worker_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("completed_at", models.DateTimeField()),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="worker_earnings",
                        to="bookings.booking",
                    ),
                ),
                (
                    "schedule",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="worker_earning",
                        to="bookings.bookingschedule",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="worker_earnings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "worker_earnings",
                "ordering": ["-completed_at"],
                "indexes": [
                    models.Index(
                        fields=["worker", "completed_at"],
                        name="we_worker_completed_idx",
                    ),
                    models.Index(
                        fields=["worker", "payment_method", "settled_at"],
                        name="we_worker_settle_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("gross_amount__gte", 0)),
                        name="worker_earnings_gross_check",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "gross_amount",
                                django.db.models.expressions.CombinedExpression(
                                    models.F("worker_amount"),
                                    "+",
                                    models.F("commission_amount"),
                                ),
                            )
                        ),
                        name="worker_earnings_split_check",
                    ),
                ],
            },
        ),
    ]
