# Generated by Django 6.1 on 2026-10-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0002_alter_wallettransaction_type_workerearning"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettransaction",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
