# Generated by Django 6.1 on 2026-10-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0003_wallettransaction_idempotency_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="workerearning",
            name="wallet_credited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
