# Generated by Django 6.1 on 2026-10-02 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0004_workerearning_wallet_credited_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettransaction",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="direction",
            field=models.CharField(
                blank=True,
                choices=[("CREDIT", "Cộng"), ("DEBIT", "Trừ")],
                default="",
                max_length=10,
            ),
        ),
    ]
