# Generated by Django 6.1 on 2026-10-03 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0005_wallettransaction_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("PAYMENT", "Thanh toán dịch vụ"),
                    ("REFUND", "Hoàn tiền"),
                    ("WITHDRAW", "Rút tiền"),
                    ("ADJUSTMENT", "Điều chỉnh"),
                    ("EARNING", "Thu nhập từ đơn"),
                    ("TOPUP", "Nạp tiền"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="WalletTopup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Chờ thanh toán"),
                            ("SUCCESS", "Thành công"),
                            ("EXPIRED", "Hết hạn"),
                            ("CANCELLED", "Đã hủy"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("order_code", models.BigIntegerField(unique=True)),
                (
                    "payment_link_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("checkout_url", models.TextField(blank=True, default="")),
                ("qr_code", models.TextField(blank=True, default="")),
                ("link_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "transaction_code",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="wallet_topups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet_transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="topup",
                        to="wallets.wallettransaction",
                    ),
                ),
            ],
            options={
                "db_table": "wallet_topups",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "link_expires_at"],
                        name="wallet_topup_status_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="wallet_topups_amount_check",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WithdrawRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROCESSING", "Đang xử lý"),
                            ("SUCCESS", "Thành công"),
                            ("FAILED", "Thất bại"),
                        ],
                        default="PROCESSING",
                        max_length=20,
                    ),
                ),
                ("reference_id", models.CharField(max_length=40, unique=True)),
                ("payout_id", models.CharField(blank=True, default="", max_length=100)),
                ("payout_mode", models.CharField(default="mock", max_length=10)),
                ("bank_bin", models.CharField(max_length=10)),
                ("bank_name", models.CharField(blank=True, default="", max_length=150)),
                (
                    "account_holder_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("account_number_encrypted", models.TextField()),
                (
                    "account_number_last4",
                    models.CharField(blank=True, default="", max_length=4),
                ),
                ("failure_reason", models.TextField(blank=True, default="")),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="withdraw_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet_transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="withdraw_request",
                        to="wallets.wallettransaction",
                    ),
                ),
            ],
            options={
                "db_table": "withdraw_requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="withdraw_status_idx"
                    ),
                    models.Index(
                        fields=["user", "created_at"], name="withdraw_user_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="withdraw_requests_amount_check",
                    )
                ],
            },
        ),
    ]
