# Generated by Django 6.1 on 2026-10-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0007_withdrawrequest_had_unknown_result_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workerearning",
            name="voided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
