# Generated by Django 6.1 on 2026-09-04 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='bookings.review')),
            ],
            options={
                'db_table': 'review_images',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BookingScheduleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('BEFORE', 'Trước khi làm'), ('AFTER', 'Sau khi làm'), ('ISSUE', 'Vấn đề phát sinh'), ('OTHER', 'Khác')], default='OTHER', max_length=20)),
                ('image', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='bookings.bookingschedule')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='uploaded_schedule_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'booking_schedule_images',
                'ordering': ['schedule_id', 'sort_order', 'created_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('sort_order__gte', 0)), name='booking_schedule_images_sort_order_check')],
            },
        ),
    ]
