# Generated by Django 6.1 on 2026-09-15 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ADMIN', 'Quản trị viên cấp'), ('CODE', 'Nhận bằng mã'), ('PUBLIC', 'Tự nhận công khai'), ('CAMPAIGN', 'Chiến dịch tự động')], max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Có thể sử dụng'), ('RESERVED', 'Đang được giữ'), ('USED', 'Đã sử dụng'), ('REVOKED', 'Đã thu hồi')], default='AVAILABLE', max_length=20)),
                ('reserved_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_vouchers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='bookingvoucher',
            name='booking_vouchers_booking_voucher_unique',
        ),
        migrations.RemoveConstraint(
            model_name='bookingvoucher',
            name='booking_vouchers_discount_amount_check',
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['city', 'name']},
        ),
        migrations.RemoveConstraint(
            model_name='area',
            name='areas_city_district_name_unique',
        ),
        migrations.RemoveConstraint(
            model_name='voucher',
            name='vouchers_used_count_check',
        ),
        migrations.RemoveConstraint(
            model_name='voucher',
            name='vouchers_per_user_limit_check',
        ),
        migrations.RemoveConstraint(
            model_name='voucher',
            name='vouchers_usage_limit_check',
        ),
        migrations.RenameField(
            model_name='voucher',
            old_name='usage_limit',
            new_name='issuance_limit',
        ),
        migrations.RenameField(
            model_name='voucher',
            old_name='used_count',
            new_name='issued_count',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='area',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='district',
        ),
        migrations.AddField(
            model_name='voucher',
            name='distribution_type',
            field=models.CharField(choices=[('PUBLIC', 'Công khai'), ('CODE_ONLY', 'Chỉ nhận bằng mã'), ('ASSIGNED', 'Được cấp riêng')], default='CODE_ONLY', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(fields=('city', 'name'), name='areas_city_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('issued_count__gte', 0)), name='vouchers_issued_count_check'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('issuance_limit__isnull', True), ('issuance_limit__gt', 0), _connector='OR'), name='vouchers_issuance_limit_check'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('issuance_limit__isnull', True), ('issued_count__lte', models.F('issuance_limit')), _connector='OR'), name='vouchers_issued_within_limit_check'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('discount_type', 'FIXED'), ('discount_value__lte', 100), _connector='OR'), name='vouchers_percent_value_check'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('max_discount_amount__isnull', True), ('max_discount_amount__gt', 0), _connector='OR'), name='vouchers_max_discount_amount_check'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('discount_type', 'PERCENT'), ('max_discount_amount__isnull', True), _connector='OR'), name='vouchers_fixed_max_discount_null_check'),
        ),
        migrations.AddField(
            model_name='uservoucher',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_user_vouchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uservoucher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_vouchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uservoucher',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_vouchers', to='bookings.voucher'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_voucher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='booking', to='bookings.uservoucher'),
        ),
        migrations.RemoveField(
            model_name='bookingvoucher',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='bookingvoucher',
            name='voucher',
        ),
        migrations.RemoveField(
            model_name='area',
            name='district',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='per_user_limit',
        ),
        migrations.AddConstraint(
            model_name='uservoucher',
            constraint=models.UniqueConstraint(fields=('user', 'voucher'), name='user_vouchers_user_voucher_unique'),
        ),
        migrations.DeleteModel(
            name='BookingVoucher',
        ),
    ]
