# Generated by Django 6.1 on 2026-09-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Chờ nhận việc"),
                    ("ASSIGNED", "Đã có nhân viên nhận"),
                    ("IN_PROGRESS", "Đang thực hiện"),
                    ("COMPLETED", "Hoàn thành toàn bộ"),
                    ("CANCELLED", "Đã hủy"),
                    ("FAILED", "Thất bại"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
    ]
