# Generated by Django 6.1 on 2026-09-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_complaint_updated_at_reviewimage_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='area',
            name='areas_city_district_name_unique',
        ),
        migrations.RemoveField(
            model_name='area',
            name='district',
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='district',
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['city', 'name']},
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(
                fields=('city', 'name'),
                name='areas_city_name_unique',
            ),
        ),
    ]
