# Generated by Django 6.1 on 2026-09-11

from django.db import migrations, models


def normalize_default_addresses(apps, schema_editor):
    CustomerAddress = apps.get_model('bookings', 'CustomerAddress')
    customer_ids = (
        CustomerAddress.objects
        .filter(is_active=True, is_default=True)
        .values_list('customer_id', flat=True)
        .distinct()
    )
    for customer_id in customer_ids:
        default_ids = list(
            CustomerAddress.objects
            .filter(customer_id=customer_id, is_active=True, is_default=True)
            .order_by('-updated_at', '-id')
            .values_list('id', flat=True)
        )
        if len(default_ids) > 1:
            CustomerAddress.objects.filter(id__in=default_ids[1:]).update(is_default=False)


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_district_from_addresses'),
    ]

    operations = [
        migrations.RunPython(normalize_default_addresses, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='customeraddress',
            constraint=models.UniqueConstraint(
                condition=models.Q(is_active=True, is_default=True),
                fields=('customer',),
                name='customer_addresses_one_active_default',
            ),
        ),
    ]
