# Generated by Django 6.1 on 2026-09-23 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0002_alter_customeraddress_latitude_and_more"),
        ("bookings", "0003_remove_pricing_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="delivery_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="delivery_bookings",
                to="addresses.customeraddress",
            ),
        ),
    ]
