# Generated by Django 6.1 on 2026-09-11

from django.db import migrations, models
from django.db.models import F


def mark_existing_booking_vouchers_as_used(apps, schema_editor):
    BookingVoucher = apps.get_model('bookings', 'BookingVoucher')
    BookingVoucher.objects.update(status='USED', used_at=F('created_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_customeraddress_one_active_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingvoucher',
            name='release_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingvoucher',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingvoucher',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingvoucher',
            name='status',
            field=models.CharField(
                choices=[
                    ('RESERVED', 'Đã giữ lượt'),
                    ('USED', 'Đã sử dụng'),
                    ('RELEASED', 'Đã hoàn lượt'),
                ],
                default='RESERVED',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='bookingvoucher',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            mark_existing_booking_vouchers_as_used,
            migrations.RunPython.noop,
        ),
    ]
