# Generated by Django 6.1 on 2026-09-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_alter_booking_user_voucher"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingscheduleimage",
            name="completion_note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
