# Generated by Django 6.1 on 2026-09-11 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_bookingvoucher_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='distribution_type',
            field=models.CharField(choices=[('PUBLIC', 'Công khai'), ('CODE_ONLY', 'Chỉ nhận bằng mã'), ('ASSIGNED', 'Được cấp riêng')], default='CODE_ONLY', max_length=20),
        ),
        migrations.CreateModel(
            name='UserVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('CUSTOMER_CLAIM', 'Khách hàng tự nhận'), ('ADMIN', 'Quản trị viên cấp'), ('CAMPAIGN', 'Chiến dịch tự động')], max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Có thể sử dụng'), ('REVOKED', 'Đã thu hồi')], default='AVAILABLE', max_length=20)),
                ('is_visible', models.BooleanField(default=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_user_vouchers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_vouchers', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_vouchers', to='bookings.voucher')),
            ],
            options={
                'db_table': 'user_vouchers',
                'ordering': ['-received_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'voucher'), name='user_vouchers_user_voucher_unique')],
            },
        ),
    ]
