# Generated by Django 6.1 on 2026-09-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_bookingscheduleimage_completion_note"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookingscheduleimage",
            name="completion_note",
        ),
        migrations.AddField(
            model_name="bookingschedule",
            name="completion_note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
