# Generated by Django 6.1 on 2026-09-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_voucher_distribution_type_uservoucher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customeraddress",
            name="area",
        ),
        migrations.AlterField(
            model_name="customeraddress",
            name="ward",
            field=models.CharField(max_length=100),
        ),
    ]
