# Generated by Django 6.1 on 2026-09-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_remove_bookingscheduleimage_completion_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingschedule",
            name="reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
