# Generated by Django 6.1 on 2026-09-30 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_bookingschedule_reminder_sent_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('BOOKING_CREATED', 'Tạo đơn'), ('BOOKING_UPDATED', 'Cập nhật đơn'), ('PAYMENT_UPDATED', 'Cập nhật thanh toán'), ('WORKER_CLAIMED', 'Nhân viên nhận việc'), ('WORKER_ASSIGNED', 'Admin gán nhân viên'), ('WORKER_REASSIGNED', 'Admin đổi nhân viên'), ('WORKER_UNASSIGNED', 'Admin bỏ phân công'), ('WORKER_CANCELLED', 'Nhân viên hủy nhận việc'), ('SCHEDULE_RESCHEDULED', 'Đổi lịch'), ('CHECKED_IN', 'Check-in'), ('CHECKED_OUT', 'Check-out'), ('BOOKING_CANCELLED', 'Hủy đơn'), ('BOOKING_FAILED', 'Đơn thất bại'), ('COMPLAINT_CREATED', 'Tạo khiếu nại'), ('REFUND_CREATED', 'Tạo hoàn tiền')], max_length=40)),
                ('message', models.TextField()),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_activities', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='bookings.booking')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='bookings.bookingschedule')),
            ],
            options={
                'db_table': 'booking_activities',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['booking', 'created_at'], name='ba_booking_created_idx'), models.Index(fields=['schedule', 'created_at'], name='ba_schedule_created_idx'), models.Index(fields=['event_type'], name='ba_event_type_idx')],
            },
        ),
    ]
