# Generated by Django 6.1 on 2026-09-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_bookingactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingactivity',
            name='event_type',
            field=models.CharField(choices=[('BOOKING_CREATED', 'Tạo đơn'), ('BOOKING_UPDATED', 'Cập nhật đơn'), ('PAYMENT_UPDATED', 'Cập nhật thanh toán'), ('WORKER_CLAIMED', 'Nhân viên nhận việc'), ('WORKER_ASSIGNED', 'Admin gán nhân viên'), ('WORKER_REASSIGNED', 'Admin đổi nhân viên'), ('WORKER_UNASSIGNED', 'Admin bỏ phân công'), ('WORKER_CANCELLED', 'Nhân viên hủy nhận việc'), ('SCHEDULE_RESCHEDULED', 'Đổi lịch'), ('CHECKED_IN', 'Check-in'), ('CHECKED_OUT', 'Check-out'), ('BOOKING_CANCELLED', 'Hủy đơn'), ('BOOKING_FAILED', 'Đơn thất bại'), ('COMPLAINT_CREATED', 'Tạo khiếu nại'), ('REFUND_CREATED', 'Tạo yêu cầu hoàn tiền'), ('REFUND_COMPLETED', 'Đã hoàn tiền')], max_length=40),
        ),
    ]
