# Generated by Django 6.1 on 2026-10-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0010_alter_bookingactivity_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="refunded_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
