# Generated by Django 6.1 on 2026-09-03 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_data', models.JSONField(blank=True, null=True)),
                ('ai_result', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Thành công'), ('NO_CANDIDATE', 'Không có ứng viên'), ('FAILED', 'Thất bại')], default='SUCCESS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ai_assignment_logs', to='bookings.booking')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='requested_ai_assignment_logs', to=settings.AUTH_USER_MODEL)),
                ('selected_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='selected_ai_assignment_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_assignment_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Đang mở'), ('CLOSED', 'Đã đóng')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chatbot_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chatbot_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('CUSTOMER', 'Khách hàng'), ('BOT', 'Bot'), ('SYSTEM', 'Hệ thống')], max_length=20)),
                ('message', models.TextField()),
                ('intent', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='messages', to='ai_engine.chatbotsession')),
            ],
            options={
                'db_table': 'chatbot_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
