# Generated by Django 6.1 on 2026-09-15 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_engine', '0001_initial'),
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiassignmentlog',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='requested_ai_assignment_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiassignmentlog',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ai_assignment_logs', to='bookings.bookingschedule'),
        ),
        migrations.AddField(
            model_name='aiassignmentlog',
            name='selected_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='selected_ai_assignment_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatbotsession',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chatbot_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatbotmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='messages', to='ai_engine.chatbotsession'),
        ),
    ]
