# Generated by Django 6.1 on 2026-10-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbotmessage',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AddField(
            model_name='chatbotmessage',
            name='cards',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='chatbotmessage',
            name='client_message_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbotmessage',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Đang xử lý'), ('COMPLETED', 'Hoàn thành'), ('FAILED', 'Thất bại')], default='COMPLETED', max_length=20),
        ),
        migrations.AddField(
            model_name='chatbotsession',
            name='title',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddIndex(
            model_name='chatbotmessage',
            index=models.Index(fields=['session', 'id'], name='chatbot_message_session_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatbotmessage',
            constraint=models.UniqueConstraint(fields=('session', 'client_message_id'), name='chatbot_client_message_unique'),
        ),
    ]
