# Generated by Django 6.1 on 2026-09-17 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('services', '0002_alter_service_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='registered_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_workers', to='services.service'),
        ),
    ]
