# Generated by Django 6.1 on 2026-09-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_workerprofile_registered_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Đang hoàn thiện'), ('PENDING', 'Chờ duyệt'), ('ACTIVE', 'Đang hoạt động'), ('REJECTED', 'Bị từ chối'), ('SUSPENDED', 'Tạm khóa')], default='DRAFT', max_length=20),
        ),
    ]
