# Generated by Django 6.1 on 2026-09-04 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_options_remove_user_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerVerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('IDENTITY_FRONT', 'CCCD/CMND mặt trước'), ('IDENTITY_BACK', 'CCCD/CMND mặt sau'), ('CERTIFICATE', 'Chứng chỉ'), ('BACKGROUND_CHECK', 'Xác minh lý lịch'), ('OTHER', 'Khác')], default='OTHER', max_length=30)),
                ('file', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('IMAGE', 'Hình ảnh'), ('PDF', 'PDF'), ('OTHER', 'Khác')], default='OTHER', max_length=30)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='verification_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'worker_verification_documents',
            },
        ),
    ]
