# Generated by Django 6.1 on 2026-09-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_workerprofile_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="workerprofile",
            name="rejected_fields",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Map field_name -> ghi chú admin, chỉ có giá trị khi status=REJECTED.",
            ),
        ),
    ]
