# Generated by Django 6.1 on 2026-09-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
