# Generated by Django 6.1 on 2026-09-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_passwordresetotp_verified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='status',
            field=models.CharField(
                choices=[
                    ('DRAFT', 'Đang hoàn thiện hồ sơ'),
                    ('PENDING', 'Chờ duyệt'),
                    ('ACTIVE', 'Đang hoạt động'),
                    ('REJECTED', 'Bị từ chối'),
                    ('SUSPENDED', 'Tạm khóa'),
                ],
                default='DRAFT',
                max_length=20,
            ),
        ),
    ]
