# Generated by Django 6.1 on 2026-09-11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_workerprofile_onboarding_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerprofile',
            name='district',
        ),
    ]
