# Generated by Django 6.1 on 2026-10-03 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0011_booking_refunded_amount"),
        ("notifications", "0003_notificationpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="related_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="bookings.bookingschedule",
            ),
        ),
    ]
