"""Reviewed seed examples; changing these requires rerunning moderation tests.

These are reference sentences, not training data or an evaluation dataset.
"""

VIOLATION_SAMPLES = (
    ('EXTERNAL_CONTACT', 'Kết bạn Zalo với em để liên hệ riêng nhé'),
    ('EXTERNAL_CONTACT', 'Cho em số điện thoại để gọi riêng cho chị'),
    ('EXTERNAL_CONTACT', 'Gửi số điện thoại của chị cho em nhé'),
    ('EXTERNAL_CONTACT', 'Nhắn tin qua Facebook riêng của em nhé'),
    ('EXTERNAL_CONTACT', 'Kết bạn Facebook em tên Nguyễn Lan nhé'),
    ('EXTERNAL_CONTACT', 'Thêm Facebook em nhé'),
    ('EXTERNAL_CONTACT', 'Thêm zalo em nhé'),
    ('EXTERNAL_CONTACT', 'Telegram em là lan_clean nhắn em ở đó nhé'),
    ('EXTERNAL_CONTACT', 'Gửi tài khoản Telegram để liên hệ ngoài app'),
    ('EXTERNAL_CONTACT', 'Cho chị Zalo của em để trao đổi riêng'),
    ('EXTERNAL_CONTACT', 'Em gửi email cá nhân để chị liên hệ nhé'),
    ('EXTERNAL_CONTACT', 'Liên hệ qua Messenger của chị nhé'),
    ('EXTERNAL_CONTACT', 'Cho em số di động của chị để gọi nhé'),
    ('EXTERNAL_CONTACT', 'Gửi chị số liên lạc riêng của em'),
    ('EXTERNAL_CONTACT', 'Chị tìm tài khoản Instagram của em nhé'),
    ('EXTERNAL_CONTACT', 'Nhắn qua WhatsApp riêng của em nhé'),
    ('EXTERNAL_CONTACT', 'Mình trao đổi qua Zalo cho tiện nhé'),
    ('OFF_PLATFORM_PAYMENT', 'Chị chuyển tiền riêng cho em nhé'),
    ('OFF_PLATFORM_PAYMENT', 'Chuyển khoản trực tiếp vào tài khoản cá nhân của em'),
    ('OFF_PLATFORM_PAYMENT', 'Chị trả tiền riêng cho em khỏi thanh toán trên app'),
    ('OFF_PLATFORM_PAYMENT', 'Em gửi số tài khoản chị chuyển thẳng cho em'),
    ('OFF_PLATFORM_PAYMENT', 'Thanh toán ngoài app để không mất phí nhé'),
    ('OFF_PLATFORM_PAYMENT', 'Chị đưa tiền mặt riêng cho em bỏ qua hệ thống'),
    ('OFF_PLATFORM_PAYMENT', 'Chuyển tiền vào tài khoản của chị thay vì trả trên app'),
    ('OFF_PLATFORM_PAYMENT', 'Tiền công chị chuyển riêng cho em sau khi dọn'),
    ('OFF_PLATFORM_PAYMENT', 'Mình thanh toán riêng không cần qua CleanWise'),
    ('OFF_PLATFORM_PAYMENT', 'Trả trực tiếp cho em không cần thanh toán qua ứng dụng'),
    ('OFF_PLATFORM_SOLICITATION', 'Lần sau chị đặt trực tiếp với em khỏi qua app'),
    ('OFF_PLATFORM_SOLICITATION', 'Chị thuê riêng em cho rẻ nhé'),
    ('OFF_PLATFORM_SOLICITATION', 'Hủy đơn trên app rồi thuê riêng em nhé'),
    ('OFF_PLATFORM_SOLICITATION', 'Chị hủy lịch rồi mình làm riêng nhé'),
    ('OFF_PLATFORM_SOLICITATION', 'Lần sau mình làm riêng cho tiện nhé'),
    ('OFF_PLATFORM_SOLICITATION', 'Đặt riêng với em sẽ rẻ hơn trên app'),
    ('OFF_PLATFORM_SOLICITATION', 'Chị gọi riêng em đến dọn không cần đặt trên app'),
    ('OFF_PLATFORM_SOLICITATION', 'Thuê trực tiếp em để khỏi mất phí nền tảng'),
    ('OFF_PLATFORM_SOLICITATION', 'Mình bỏ qua app rồi thỏa thuận giá riêng nhé'),
    ('OFF_PLATFORM_SOLICITATION', 'Chị đặt ngoài ứng dụng em giảm giá cho chị'),
    ('OFF_PLATFORM_SOLICITATION', 'Lần sau cứ thuê em không cần qua CleanWise'),
    ('OFF_PLATFORM_SOLICITATION', 'Hủy booking này rồi em làm giá riêng cho chị'),
    ('OFF_PLATFORM_SOLICITATION', 'Đừng đặt qua app nữa cứ thuê riêng em'),
    ('OFF_PLATFORM_SOLICITATION', 'Em nhận dọn riêng ngoài hệ thống nhé'),
    ('OFF_PLATFORM_SOLICITATION', 'Mình giao dịch ngoài nền tảng cho tiết kiệm'),
    ('OFF_PLATFORM_SOLICITATION', 'Chị muốn thuê em riêng vào lần tới'),
    ('OFF_PLATFORM_SOLICITATION', 'Chị đặt trực tiếp em lần sau giá tốt hơn'),
    ('OFF_PLATFORM_SOLICITATION', 'Không cần tạo đơn mình thỏa thuận riêng nhé'),
    ('OFF_PLATFORM_SOLICITATION', 'Mình làm ngoài app để không bị trừ phí'),
    ('OFF_PLATFORM_SOLICITATION', 'Chị thuê ngoài app em lấy giá thấp hơn'),
    ('OFF_PLATFORM_SOLICITATION', 'Nhắn riêng em để đặt lịch dọn nhà nhé'),
    ('OFF_PLATFORM_SOLICITATION', 'Mình hẹn dọn riêng không cần qua ứng dụng'),
    ('OFF_PLATFORM_SOLICITATION', 'Em làm riêng cho chị bỏ qua CleanWise'),
    ('OFF_PLATFORM_SOLICITATION', 'Lần tới thuê riêng chị giảm tiền công cho'),
    ('OFF_PLATFORM_PAYMENT', 'Chị hủy trên app rồi trả riêng cho em'),
)

ALLOWED_SAMPLES = (
    'Chị đừng đặt riêng với em cứ đặt qua app nhé',
    'Không được trao đổi số điện thoại ngoài app',
    'Đừng chuyển tiền riêng cho nhân viên',
    'Không nên kết bạn Zalo với khách hàng',
    'Chị không muốn thuê riêng em',
    'Em không nhận làm riêng ngoài app',
    'CleanWise cấm giao dịch ngoài nền tảng',
    'Vui lòng không chia sẻ email cá nhân',
    'Không gửi tài khoản Telegram để liên hệ riêng',
    'Không thanh toán ngoài app nhé',
    'Chị đã chuyển khoản trên app rồi',
    'Chị thanh toán qua ứng dụng nhé',
    'Thanh toán trên CleanWise có thành công chưa',
    'Em kiểm tra trạng thái thanh toán giúp chị',
    'Tôi cần hỗ trợ hoàn tiền đơn đã hủy',
    'Chị hủy đơn vì đặt nhầm lịch',
    'Hủy lịch trên app rồi đặt lại trên app nhé',
    'Em hướng dẫn chị hủy đơn trong ứng dụng',
    'Chị muốn đổi giờ dọn nhà',
    'Lần sau chị đặt lại trên app nhé',
    'Em đến lúc 9h30 phòng 1205 tầng 12',
    'Nhà chị diện tích 100 mét vuông',
    'Địa chỉ phục vụ là 123 Nguyễn Trãi',
    'Em đến trực tiếp địa chỉ trong đơn',
    'Mã đơn của chị là CW202610090001',
    'Giá dịch vụ là 500000 đồng',
    'Nhà có hai phòng ngủ và một phòng khách',
    'Chị cần dọn riêng phòng bếp trước',
    'Em làm riêng khu vực ban công giúp chị',
    'Chị để dụng cụ riêng trong phòng kho',
    'Ứng dụng có đăng nhập bằng Facebook không',
    'Zalo có phải kênh hỗ trợ chính thức không',
    'Em nhắn chị trong app khi đến nơi nhé',
    'Chị gọi hỗ trợ qua ứng dụng giúp em',
    'Đơn tiền mặt chị thanh toán trực tiếp cho em theo đơn trên app',
    'Chị trả tiền mặt khi hoàn thành theo phương thức trong đơn',
    'Chị gửi hướng dẫn công việc trong chat nhé',
    'Em mang theo dụng cụ vệ sinh đầy đủ',
    'Chị muốn đặt lịch hàng tuần trên CleanWise',
    'Mình trao đổi trong ứng dụng cho tiện nhé',
    'Chị muốn thuê thêm nhân viên qua app',
    'Chị đặt trực tiếp trong app giúp em nhé',
    'Chị trả tiền theo hướng dẫn thanh toán của app',
    'Chị không cần hủy đơn nếu chỉ đổi ghi chú',
    'Tôi nhận được tin nhắn rủ giao dịch riêng và muốn báo cáo',
    'Nhân viên bị cấm nhận thanh toán riêng',
    'Chị lưu ý không thuê ngoài app để được hỗ trợ',
    'Đừng gọi riêng nhân viên hãy nhắn trong app',
    'Chị kiểm tra email xác nhận của hệ thống',
    'Tôi muốn báo cáo lời mời kết bạn Facebook',
)
