# Generated by Django 6.1 on 2026-09-22 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_chat_assignments(apps, schema_editor):
    database = schema_editor.connection.alias
    Conversation = apps.get_model('chat', 'ChatConversation')
    Message = apps.get_model('chat', 'ChatMessage')
    Link = apps.get_model('chat', 'ChatConversationAssignment')
    Assignment = apps.get_model('worker', 'BookingAssignment')

    # Existing conversations might have been keyed by booking. Merge those
    # belonging to the same customer and worker before adding the pair key.
    pairs = Conversation.objects.using(database).values_list('customer_id', 'worker_id').distinct()
    for customer_id, worker_id in pairs:
        conversations = list(Conversation.objects.using(database).filter(
            customer_id=customer_id, worker_id=worker_id,
        ).order_by('id'))
        primary = conversations[0]
        for duplicate in conversations[1:]:
            Message.objects.using(database).filter(conversation_id=duplicate.id).update(conversation_id=primary.id)
            if duplicate.status == 'ACTIVE' and primary.status != 'ACTIVE':
                primary.status = 'ACTIVE'
                primary.save(using=database, update_fields=['status'])
            if duplicate.booking_id:
                for assignment in Assignment.objects.using(database).filter(
                    schedule__booking_id=duplicate.booking_id, worker_id=worker_id,
                ).exclude(status__in=['PENDING', 'REJECTED', 'EXPIRED']):
                    Link.objects.using(database).get_or_create(
                        assignment_id=assignment.id, defaults={'conversation_id': primary.id},
                    )
            duplicate.delete(using=database)
        if primary.booking_id:
            for assignment in Assignment.objects.using(database).filter(
                schedule__booking_id=primary.booking_id, worker_id=worker_id,
            ).exclude(status__in=['PENDING', 'REJECTED', 'EXPIRED']):
                Link.objects.using(database).get_or_create(
                    assignment_id=assignment.id, defaults={'conversation_id': primary.id},
                )

    for assignment in Assignment.objects.using(database).select_related(
        'worker', 'schedule__booking__customer',
    ).filter(status='ACCEPTED').iterator():
        customer = assignment.schedule.booking.customer
        worker = assignment.worker
        conversation, _ = Conversation.objects.using(database).get_or_create(
            customer_id=customer.id, worker_id=worker.id,
        )
        Link.objects.using(database).get_or_create(
            assignment_id=assignment.id, defaults={'conversation_id': conversation.id},
        )
        start = timezone.localtime(assignment.schedule.scheduled_start).strftime('%d/%m/%Y %H:%M')
        worker_name = f'{worker.first_name} {worker.last_name}'.strip() or worker.username
        customer_name = f'{customer.first_name} {customer.last_name}'.strip() or customer.username
        Message.objects.using(database).get_or_create(
            related_assignment_id=assignment.id, recipient_id=customer.id,
            defaults={
                'conversation_id': conversation.id,
                'message_type': 'SYSTEM',
                'message': f'Nhân viên {worker_name} đã nhận lịch làm ngày {start}. Bạn có thể liên hệ với nhân viên tại đây.',
            },
        )
        Message.objects.using(database).get_or_create(
            related_assignment_id=assignment.id, recipient_id=worker.id,
            defaults={
                'conversation_id': conversation.id,
                'message_type': 'SYSTEM',
                'message': f'Bạn đã nhận lịch làm ngày {start} của khách hàng {customer_name}. Hãy liên hệ với khách hàng để trao đổi.',
            },
        )
        Conversation.objects.using(database).filter(pk=conversation.id).update(updated_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('worker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_conversation_assignments',
            },
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='received_chat_system_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='related_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chat_system_messages', to='worker.bookingassignment'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'Văn bản'), ('IMAGE', 'Hình ảnh'), ('FILE', 'Tệp'), ('SYSTEM', 'Hệ thống')], default='TEXT', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'id'], name='chat_message_convo_id_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'recipient', 'is_read'], name='chat_message_unread_idx'),
        ),
        migrations.AddField(
            model_name='chatconversationassignment',
            name='assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='chat_link', to='worker.bookingassignment'),
        ),
        migrations.AddField(
            model_name='chatconversationassignment',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_links', to='chat.chatconversation'),
        ),
    ]
